### ISSUE TITLE
Poly Marker Queue Length Question

### ISSUE THREAD

**Issue by wkmustahs21** [homonecloco/polymarker_server#1]
Hi 

I have a quick question: does the queue length indicate the number of people ahead of me? I submitted 9 jobs last night at around 9:15 pm and have still not gotten an update on results yet. The queue length is about 300. (it's not my first time using this tool .... I used a couple of weeks ago submitting more than 50 jobs and I got results in less than a minute).

Is there an issue of some sort?

**Comment by homonecloco** [comment]
Hi,
Thanks for getting in touch. The queue number is the number of jobs in the queue at the time of submission, unfortunately I haven’t figure out how to keep that updated. I’ll have a look on the servers, but we are having some internal issues in the institute. I’ll update this once it is resolved.
Best,

**Comment by wkmustahs21** [comment]
Oh ok ...I checked this morning and jobs are 325 now. If you can fix this
and get it moving along that would be great.
Have a pleasant day!
Wardah Mustahsan

**Comment by wkmustahs21** [comment]
Hi Ricardo

So I got email notifications for my poly marker jobs but all of them say:
'502 Bad Gateway'.... what does this mean?
Have a pleasant day!
Wardah Mustahsan

**Comment by homonecloco** [comment]
Hi, 
I was doing some mantainace, and the web page was done for a bit. But now the results should be available. 
Best, 
Ricardo.
